compressionLevel: mixed

enableGlobalCache: false

# Use system yarn instead of vendored version
# yarnPath: .yarn/releases/yarn-4.3.1.cjs

# Enforce yarn as the only package manager
nodeLinker: node-modules